### ISSUE TITLE
Selected event overlay doesn't match event overlay

### ISSUE THREAD

**Issue by detouched** [signalfx/terraform-provider-signalfx#26]
Dashboard can have `event_overlay` as well as `selected_event_overlay`, and the docs state they have same fields:

> `selected_event_overlay` - (Optional) Defines event overlays which are enabled by default. See `event_overlay` for a definition of fields.

However, unlike [`event_overlay`](https://github.com/signalfx/terraform-provider-signalfx/blob/12d56df44cf25bf97792e36f2881a88870c8af03/signalfx/dashboard.go#L288), [`selected_event_overlay`](https://github.com/signalfx/terraform-provider-signalfx/blob/12d56df44cf25bf97792e36f2881a88870c8af03/signalfx/dashboard.go#L351) lacks `line`, `label`, and `color` attributes.

**Comment by cory-signalfx** [comment]
Indeed! Lemme look at the docs and such to verify behavior…

**Comment by cory-signalfx** [comment]
Ok, looks like the API only supports those options on the `selectedEventOverlays`, so I'll adjust the docs here to not be confusing.

**Comment by detouched** [comment]
Hey @cory-signalfx,

I tried the following, as your change suggests (if I read it correctly):
```
  event_overlay {
    signal = "Initialised lifecycle hook"
    label = "Started"
    color = "orange"
    line = true
    source {
      property = "service_id"
      values = ["some-service"]
    }
  }

  selected_event_overlay {
    signal = "Initialised lifecycle hook"
    property = "service_id"
    values = ["some-service"]
  }
```
I believe this is what you meant by:
> Any overlay specified here should have an accompanying entry in `event_overlay.source`, which mirrors the fields here.

However this raises an error:
```
Error: module.dashboards.signalfx_dashboard.some_service: selected_event_overlay.0: invalid or unknown key: property
Error: module.dashboards.signalfx_dashboard.some_service: selected_event_overlay.0: invalid or unknown key: values
```

So in fact these attributes of `selected_event_overlay` should be inside of `source` element.

**Comment by cory-signalfx** [comment]
Eep, I must've been doing two many things at once when I last modified that. I've just pushed a commit that adjusts things a bit. This one looks right to me.
