### ISSUE TITLE
Support for Event Feed chart type in the Terraform provider

### ISSUE THREAD

**Issue by adamorabi** [signalfx/terraform-provider-signalfx#27]
It looks like the terraform signalfx provider (https://github.com/signalfx/terraform-provider-signalfx) has no support for the Event Feed chart type and there is no documentation for the REST API (https://developers.signalfx.com/charts_reference.html#tag/Create-Single-Chart) for option.type = "events" either.

I would like to be able to fully manage my dashboard as code using terraform so I would like to request this feature for completeness.

**Comment by cory-signalfx** [comment]
Makes sense! I've looked internally and found that this was missing from the docs and filed a ticket (DOCS-622) to fix that side up.

I'll also add it to the provider soon, maybe next week?
