### ISSUE TITLE
Add support for importing

### ISSUE THREAD

**Issue by juliawong** [signalfx/terraform-provider-signalfx#36]
We'd love to see the SFx Terraform provider support [importing](https://www.terraform.io/docs/import/usage.html). This would allow us to run something like `terraform import <name_of_resource> <remote_id>` and have it added to the TF file and state. 

https://github.com/signalfx/signalfx-to-terraform bridges the gap here but it'd be awesome to see it all integrated into the provider. This would allow us to create new dashboards or detectors via the UI and easily get the config into Terraform. :)

**Comment by cory-signalfx** [comment]
A great idea! I'll get on this in the next week or two.

**Comment by cory-signalfx** [comment]
The workflow for this is:

* Add a placeholder resource to the file, like `resource "signalfx_detector" "fart" {}`
* Run `terraform import signalfx_detector.fart`
* Run `terraform state show signalfx_detector.fart`
* Grab the output into your clipbard
* Paste the clipboard over the placeholder above, removing the `id = XXX` line.
* Run `terraform plan` to ensure everything worked. Sometimes you'll want to `terraform apply` to pick up some defaults.
* Profit!
