### ISSUE TITLE
Terraform Provider Development Program Review 

### ISSUE THREAD

**Issue by cgriggs01** [signalfx/terraform-provider-signalfx#37]
Hi SignalFX Team,

👋 My name is Chris, I'm a member of the Partner team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the master branch at git commit `c6989b8`.

You have the option of making these changes directly to master, or creating a new branch named something like `terraform-provider-review`. Once the provider has finished the certification process we'll clone this repository and move it to the github.com/terraform-providers/ organization. 

- [x] You are already using Go Modules for managing dependancies, which is great but do to some of our current system, we are still requiring that all dependancies are checked into a `vendor/` director within the repo. This can be done by running `go mod vendor`

- [x] Now that we have released [Terraform 0.12](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html), you can now upgrade to the new Terraform SDK. 

- [x]  The GNUmakefile is standard across all Terraform providers and many of the make targets are used throughout the build/test/release processes, feel free to copy the [NULL provider makefile](https://github.com/terraform-providers/terraform-provider-tls/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=signalfx
         - Along with the makefile there are four bash scripts in a `scripts/` directory that are used in different processes these can all be copied from the [NULL provider](https://github.com/terraform-providers/terraform-provider-null/tree/master/scripts). Make sure that these script files are executable by all users. 

- [x] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “0.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [x] All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please add a .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [x] There is a standard README.md for all of the official providers, see [Null provider README.md](https://github.com/terraform-providers/terraform-provider-null/blob/master/README.md)

- [x] The provider documentation is great, but you'll have to get it into the Terraform.io format. Website documentation is stored in a `website/` directory.  Within the website directory, there must be an `signalfx.erb` layout file similar top [consul.erb](https://github.com/terraform-providers/terraform-provider-consul/blob/master/website/consul.erb) that is used to define the sidebar directory of the documentation. 
     - Along with the layout file will be a `docs/` directory which is to store all of the Markdown documentation files
     - Inside of the docs/ directory must be an index.html.markdown file, this is the provider main page and is used to document the high-level use of the integration and provider credentials references.(basically everything that is in your readme)
     - A `r/` directory is used to store all the resource_<name>.html.markdown documentation files. Each resource documentation page should have an example implementation and list out all of the attributes and arguments of the resource. 
     - A `d/` directory is used to store all the data_source_<name>.html.markdown doc files. Each data source documentation page should have an example implementation and list out all of the attributes and arguments of the resource
     - Each .html.markdown file must have a head to declare the layout of the webpage. 
     ```
     ---
     layout: "signalfx"
     page_title: "SignalFX: signalfx_detector"
     sidebar_current: "docs-signalfx-resource-detector"
     description: |-
       Allows Terraform to create a Detector resource
     ---
     ```
- [x] The resource file naming convention is as follows, `resource_providername_resource_name.go` which means the file `detector.go` should be named `resource_signalfx_detector.go` and its corresponding acceptance test should be named `resource_signalfx_detector_test.go` , this should be follows across all resource files. 

- [x] For each schema, the `Required` arguments should be defined first, then `Optional` arguments are next, then Computed attributes last. 

- [x] Its looked like you are using standard CRUD methods that are called from each resource CRUD method. So I'm not sure on which level you'll want to implement this on but the CREATE method of any Resource should at least return the results of it’s own READ method. In certain cases it may need to return the results of the UPDATE method, depending on if the CREATE method is capable of setting all possible configuration values. If for example the API call to create Resource only allows basic creation, the remaining configuration is applied via update, then CREATE should return UPDATE, and UPDATE should return READ. [AWS Security Group Resource](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_security_group.go) is an example of this; the CREATE only allows creating a Security Group with a name and description, and we must make other API calls to apply the rules. Thus, CREATE returns the results of UPDATE.

- [x] If a resource cannot be found(404) in the read function, we should do a d.SetId("") to remove it from the statefile. You also wouldn't need to return an error then. Terraform will just treat it as a resource that never existed and try and create it.

- [x] Do I need to swet up infrastructure in GCP or have a PagerDuty account to run those acceptance tests?

Thank you for your work on this. Let me know if you have and question, I'm looking forward to certifying this provider and getting out to the broader terraform community. 

Best, Chris

**Comment by cory-signalfx** [comment]
Thanks a ton @cgriggs01! I'll get started on this immediately and hit you back sometime next week. I'm in SF for an office visit, so will be moving a bit slower than usual. :)

**Comment by cory-signalfx** [comment]
Note that Terraform 0.12 is being tracked separately in #32. I will keep it rebased against master for 0.11 users, which I am certain we have.

**Comment by cory-signalfx** [comment]
And @cgriggs01 yes, you will need a GCP and PagerDuty resource for this to work. Other integrations of ours — which are to be added — will likely also need that. Unsure how to proceed with that. :/

**Comment by cgriggs01** [comment]
Cory, thats not a problem. But the 0.12 provider build should be backward compatible with older TF versions. Just as an FYI, we are only releasing 0.12 ready providers moving forward.

**Comment by cory-signalfx** [comment]
@cgriggs01 Perfect, I'll of course wrap all this up in a branch for you when I get closer to completion. Thanks for the clarification!

**Comment by cgriggs01** [comment]
> And @cgriggs01 yes, you will need a GCP and PagerDuty resource for this to work. Other integrations of ours — which are to be added — will likely also need that. Unsure how to proceed with that. :/

Would if be possible to have a TF config that deploys the required GCP and PagerDuty infra to run the tests?

**Comment by cory-signalfx** [comment]
> Would if be possible to have a TF config that deploys the required GCP and PagerDuty infra to run the tests?

Yeah, I guess so. We'll just need to also include the requisite keys… is that something you can provide if I give you the resources?

**Comment by cgriggs01** [comment]
> Yeah, I guess so. We'll just need to also include the requisite keys… is that something you can provide if I give you the TF config?

Yes, I definitely have creds for GCP, and will probably be able to get some for PagerDuty. What about Slack?

**Comment by cory-signalfx** [comment]
> Yes, I definitely have creds for GCP, and will probably be able to get some for PagerDuty. What about Slack?

Excellent! Slack is no problem, as it's just any valid URL, so you can fake it.

**Comment by cory-signalfx** [comment]
As you can see I'm working my way through this list with PRs. Happily, one doesn't need a PR:

> If a resource cannot be found(404) in the read function, we should do a d.SetId("") to remove it from the statefile. 

The [common read code](https://github.com/signalfx/terraform-provider-signalfx/blob/master/signalfx/util.go#L193) handles this for us. If we find a 404 then we `SetId("")` and error stays `nil`. I'm gonna check that one off, lemme know if I've misunderstood!

**Comment by cory-signalfx** [comment]
Hey @cgriggs01, do you have any suggestions on local testing of the site? My [builds are failing](https://travis-ci.org/signalfx/terraform-provider-signalfx/builds/545003244?utm_source=github_status&utm_medium=notification) and short of running `make website-test` and getting some opaque Docker container I'm not sure of next steps! It seems to use Middleman, but has some magic around this test.

**Comment by cory-signalfx** [comment]
Hey @cgriggs01, it looks like for #39 to start passing we have a chicken and egg problem. The submodule bits for the provider don't exist in the website repo yet, so none of the tests can pass.

**Comment by cgriggs01** [comment]
> Hey @cgriggs01, it looks like for #39 to start passing we have a chicken and egg problem. The submodule bits for the provider don't exist in the website repo yet, so none of the tests can pass.

If you're referring to the make target `website-test`, yes that will not pass until the providers website docs have been officially integrated into the terraform.io framework. So no worry there

**Comment by cgriggs01** [comment]
You're doing great so far! Once you have written a TF config for the acceptance testing infrastructure, you should put that into a `test-infra/` directory within this repository.

**Comment by cory-signalfx** [comment]
Marking the integration stuff done since we've discussed alternate plans.

**Comment by cory-signalfx** [comment]
Going to close this, as I think we're done here. If there are other things we can deal with them via email, another issue, or reopening this one.
