### ISSUE TITLE
Missing "Refresh Every" on signalfx_heatmap_chart

### ISSUE THREAD

**Issue by clayembry** [signalfx/terraform-provider-signalfx#41]
I'm trying to terraform a signalfx_heatmap_chart. In the SignalFx UI, under Chart Options -> Visualization Options, I can set the "Refresh Every" field to 1s, 5s, 1m, 5m, 1h. I would like to set it to 1m, but I can't see any way to do that in terraform: https://github.com/signalfx/terraform-provider-signalfx/blob/master/docs/resources/heatmap_chart.md

I thought it might be "minimum_resolution", which I tried setting to 60, but that did not set the "Refresh Every" field.

**Comment by cory-signalfx** [comment]
Thanks for reporting @clayembry, I'll check on this today and figure out what's up. :)

**Comment by cory-signalfx** [comment]
A quick check before a meeting says this should be the option `refreshInterval` which is not in the options. I'll get that added and shoot out a PR today or tomorrow. Sorry for thart!

**Comment by cory-signalfx** [comment]
Hey @clayembry! Turns out this feature is -- [according to the docs](https://developers.signalfx.com/charts_reference.html) only support on list and single value charts:

> Note This option is only available if `options.type` is `List` or `SingleValue`.

So in this case, it being absent is on purpose!

**Comment by clayembry** [comment]
I think it's a bug, but I guess that means it's not a terraform provider bug. It's actually a product API bug. Because I can definitely set that via the UI for heatmap charts. I will raise the bug with the product. Thanks.

![image](https://user-images.githubusercontent.com/12000442/59445348-1e6c5280-8dc5-11e9-8351-6114229bdf1f.png)

**Comment by cory-signalfx** [comment]
Ah! Let me reopen this and do some testing. I'm quite happy to add the feature to Terraform and make a DOCS ticket internally. :)
