### ISSUE TITLE
Mirrored dashboard support

### ISSUE THREAD

**Issue by MovieStoreGuy** [signalfx/terraform-provider-signalfx#43]
This would be awesome if we can support this within the terraform provider.

**Comment by cory-signalfx** [comment]
Excellent suggestion, I'll get it done.

**Comment by cory-signalfx** [comment]
I'm thinking this will look something like:

```
resource "signalfx_mirrored_dashboard" "fartboard" {
  dashboard = "abc123"
  description_override = "mirror's description"
  name_override = "mirror's name"
  filters_override: { … }
}
```

But still learning how these work in the API!

**Comment by cory-signalfx** [comment]
Closing for https://github.com/terraform-providers/terraform-provider-signalfx/issues/4
