### ISSUE TITLE
Need support for Calendar Time Zone for time chart

### ISSUE THREAD

**Issue by zimingw** [signalfx/terraform-provider-signalfx#51]
Hi, I have a question about terraform for SignalFX.  How can I set the Calendar Time Zone of a time chart using terraform?

**Comment by cory-signalfx** [comment]
Hey @zimingw! I think what we're looking for here is support for the `programOptions.timezone` parameter which was added with calendar support. As you are suggesting, that is currently absent. Consider this an ask and I'll get to it as quick as I can!

**Comment by zimingw** [comment]
Thanks @cory-signalfx for fast response!
