### ISSUE TITLE
Document watermarks

### ISSUE THREAD

**Issue by cory-signalfx** [signalfx/terraform-provider-signalfx#6]
[This PR from Stripe](https://github.com/stripe/terraform-provider-signalform/pull/2) never got clear docs. Add them!

**Comment by tiedotguy** [comment]
What's the intent behind that PR? It looks like there's nothing that actually consumes the additional watermarks, it just allows tf to not consider it an error?

**Comment by cory-signalfx** [comment]
It was a hedge against a future when SignalFx improves watermark support.

**Comment by tiedotguy** [comment]
Well we do have a feature request in for it too... :)

**Comment by cory-signalfx** [comment]
Closing for move to https://github.com/terraform-providers/terraform-provider-signalfx
