### ISSUE TITLE
List chart: missing secondary visualization options

### ISSUE THREAD

**Issue by detouched** [signalfx/terraform-provider-signalfx#62]
Looks like there's no way to configure thresholds and colors for secondary visualization in the list chart.

E.g. if `secondary_visualization = "Radial"`, there's currently no way to make look it like this:
<img width="90" alt="Secondary visualization" src="https://user-images.githubusercontent.com/1497429/60438307-bc7c6b80-9c53-11e9-9a88-9148372626d3.png">

`color_scale` isn't allowed by the schema (works for single value chart).

**Comment by cory-signalfx** [comment]
Indeed! Over the last couple weeks of revamping in #44 I noticed that a lot of these were inconsistently available. I'll get to this soon!

**Comment by cory-signalfx** [comment]
This was done in #76
