### ISSUE TITLE
List chart: sort by plot name

### ISSUE THREAD

**Issue by detouched** [signalfx/terraform-provider-signalfx#63]
Documentation for `sort_by` parameter suggests to use metric names or value.
UI also has an option to sort by plot name. Is there a way to set up same thing in Terraform?
<img width="411" alt="Chart - Disk utilization runway (search001) 2019-07-01 23-04-09" src="https://user-images.githubusercontent.com/1497429/60438771-cf437000-9c54-11e9-81bc-bd31f046ef75.png">

Tried `+plotname`, `+plot_name` and `+plot name` but none of them worked.

**Comment by cory-signalfx** [comment]
Hey @detouched, I think you want to give it `sf_metric` for this to work. I'll keep this ticket open, however, to flag that these should be documented in `resource/list_chart`:

* `value` for Value
* `sf_originatingMetric` for Metric
* `sf_metric` for Plot Name

**Comment by detouched** [comment]
Awesome, thanks @cory-signalfx!
