### ISSUE TITLE
Terraform Provider Development Program - Final Review

### ISSUE THREAD

**Issue by cgriggs01** [signalfx/terraform-provider-signalfx#74]
Hey Team, 

I took another pass at the provider and have a few items to ask about. 

- [ ] The first will be the acceptace tests, I was able to run them from my local machine, but have a number of reoccurring failed tests.  I've included the test output in [testout.txt](https://github.com/signalfx/terraform-provider-signalfx/files/3357037/testout.txt). Let me know if you have any idea of what the issue is.

- [ ] If a resource cannot be found(404) in the read function, we should do a d.SetId("") to remove it from the statefile
> The common read code handles this for us. If we find a 404 then we SetId("") and error stays nil. I'm gonna check that one off, lemme know if I've misunderstood!

This is a fine to use a common read function for this, but I am only seeing the resourceRead() function is only being called in the [integration resource](https://github.com/signalfx/terraform-provider-signalfx/blob/master/signalfx/resource_signalfx_integration.go#L159), this should be done within each resource READ. 

- [ ] Any code that is commented out and unused should be removed from the provider resource files. 

Thanks,
Chris

**Comment by cory-signalfx** [comment]
Eep! The 404 thing is a regression on my part, thanks for flagging.

The test failures are confusing. I'll try and repro and may need to send you a new token. Will dig in.

**Comment by cory-signalfx** [comment]
Hey @cgriggs01, is it suitable to instead implement `Exists` rather than checking the status in each `Read` function? I did that in #75 which is what I see done in other providers…

Also, pretty sure I need to send you a new key. All those test failures are on the things that talk to the API. How can I do that?

**Comment by cory-signalfx** [comment]
(I just sent another one via the webform, which I assume you can find. I used the form `SFX_AUTH_TOKEN=XXX`)

**Comment by cgriggs01** [comment]
Thanks for sending the new key over. 

Thats all the feedback I have and we can move forward to the merge and release phase. I'd suggest we begin the process today and I will create the new repository and clone/push this up to the new location, get the acceptance tests running in TeamCity then we can be ready to publish the first release and website documentation on Monday. 

Does that work for you?

**Comment by cory-signalfx** [comment]
Yeah, that works for me. I have one other patch I'm working on, but have some work to do on the client lib before I get there. Fire away!
